# Generated by Django 4.2.5 on 2023-09-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iou_track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='owe_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='owes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
