# Generated by Django 4.2.5 on 2023-09-30 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iou_track', '0002_alter_user_owe_by_alter_user_owes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user',
        ),
    ]
