# Generated by Django 4.2.5 on 2023-10-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iou_track', '0003_rename_name_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='owe_by',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='owes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
