# Generated by Django 4.2.5 on 2023-10-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iou_track', '0004_alter_user_owe_by_alter_user_owes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
