# Generated by Django 4.2.5 on 2023-10-01 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iou_track', '0005_alter_user_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='name',
        ),
    ]
